#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require "vendor/autoload.php";

$app = new Application('Building Console Application Demo', '1.0');

$app->register('sayHelloTo')
	->setDescription('Offer a greeting to a certain person')
	->addArgument('name', InputArgument::REQUIRED, 'Your Name')
	->setCode(function(InputInterface $input, OutputInterface $output) {

		$message = 'Hello, ' . $input->getArgument('name');

		$output->writeln('<info>' . $message . '</info>');
	});

$app->run();