#! /usr/bin/env php

<?php

use Acme\NewCommand;
use Symfony\Component\Console\Application;

require "vendor/autoload.php";

$app = new Application('Building Console Application Demo', '1.0');

$app->add(new NewCommand(new GuzzleHttp\Client));

$app->run();